meta_product_name: "Taa."
meta_title: "Taa. | Your ultimate daily commute !"
meta_description: "You can now choose, in all simplicity, the most sustainable route to your destiation ! "
meta_image: "taa-origin.png" # should exist in `app/assets/images/`
